require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '18.0'
prepare_react_native_project!

require_relative '../node_modules/react-native-permissions/scripts/setup'
setup_permissions(['LocationWhenInUse'])

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'bridgething' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    user_target = 'Pods-bridgething'
    %w[debug release].each do |config_name|
      xcconfig_path = File.join(__dir__, 'Pods/Target Support Files', user_target, "#{user_target}.#{config_name}.xcconfig")
      next unless File.exist?(xcconfig_path)
      include_line = %(#include "../../../Defaults.xcconfig"\n#include? "../../../Local.xcconfig")
      contents = File.read(xcconfig_path)
      next if contents.include?(include_line)
      File.write(xcconfig_path, "#{contents.rstrip}\n#{include_line}\n")
    end
  end
end
