// @generated by tools/codegen - do not edit. Run `just codegen` to regenerate.

export const UUID_FIELD_NAMES: ReadonlySet<string> = new Set([
  'connectionId',
  'id',
  'launcher',
  'overlay',
  'requestId',
  'streamId',
  'transferId',
  'tunnelId',
  'webapp',
]);
