// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Direction the accessory wants iOS to take when answering an incoming
 * call while another call is active.
 */
export type AcceptCallAction = 'accept' | 'endAndAccept';

/**
 * An album reference.
 */
export type Album = {
  id: string;
  name: string;
  /**
   * Opaque artwork asset id (`asset.get`), when known.
   */
  artworkId: string | null;
};

/**
 * Daemon-observed state of the ANCS GATT-client session against the
 * connected iPhone. iOS-only; emitted on transitions so the companion
 * app can confirm the LE-pair + ANCS authorization handshake completed.
 *
 * State machine:
 * - `Unknown`: pre-boot only (no iAP2 has ever attached this session).
 * - `Probing`: a session task is running but no determination yet,
 *   OR iAP2 just detached and we expect to re-probe on reconnect.
 * - `Authorized`: ANCS attribute fetches are succeeding.
 * - `Unauthorized`: ANCS service hidden, or auth-gate detected.
 */
export type AncsAuthState = 'unknown' | 'probing' | 'authorized' | 'unauthorized';

/**
 * Art render sizes a webapp declares so the companion warms exactly the
 * pixels it renders: hero (now-playing / detail views) and thumb (queue /
 * grid). Omitted in a manifest falls back to the canonical `{248, 96}`
 */
export type ArtProfile = { heroPx: number; thumbPx: number };

/**
 * An artist reference.
 */
export type Artist = {
  id: string;
  name: string;
  /**
   * Opaque artwork asset id (`asset.get`), when known.
   */
  artworkId: string | null;
};

export type AssetRetention =
  | { type: 'lru' }
  | { type: 'pinned' }
  | { type: 'ttl'; data: TtlRetention }
  | { type: 'persistent' };

export type AudioCapabilities = { earcons: Array<string>; voices: Array<VoiceDescriptor> };

export type AudioError =
  | { type: 'actionRejected'; data: { reason: string } }
  | { type: 'ttsFailed'; data: { reason: string } }
  | { type: 'unavailable'; data: { verb: string } }
  | { type: 'noTarget' };

export type BoolField = { key: string; label: string; default: boolean | null };

/**
 * Bridge-side identity announce
 */
export type BridgeThingMeta = {
  bridgethingVersion: string;
  libbridgethingVersion: string;
  appName: string;
  nickname: string | null;
  appVersion: string;
  daemonSha256: string | null;
  /**
   * None when no wake word model resolved, or when the one that did carries no version stamp.
   */
  wakewordModelVersion: string | null;
  osName: string;
  osVersion: string;
  osDescription: string;
  btMac: string;
  serialNumber: string;
  fccId: string;
  icId: string;
  modelName: string;
  channel: string;
  imageVariant: string;
  imageVersion: string;
  imageBuildId: string;
  imageBuildDate: string;
  imageDistro: string;
  imageMachine: string;
  discord: string;
  credits: string;
};

export type BrightnessMode = 'auto' | 'manual';

/**
 * Backlight state. `level` is the user-set value (only respected in
 * `Manual`); `effective_level` is what's actually on the panel - equal
 * to `level` in `Manual`, ALS-derived in `Auto`.
 */
export type BrightnessState = { mode: BrightnessMode; level: number; effectiveLevel: number };

/**
 * One row in a `BrowseResult`: either a folder (drilldown) or a leaf
 * item the user can play / queue / favorite.
 */
export type BrowseEntry = { type: 'folder'; data: BrowseFolder } | { type: 'item'; data: LibraryItem };

/**
 * A drilldown node. `node_id` is opaque and gateway-defined; webapps
 * pass it back as the next `browse({ node_id })` to descend. `total` is
 * the count of children behind this folder when the gateway can cheaply
 * expose it. `preview_children` is an inline first-N slice of those
 * children so home-shelf shapes don't need a separate drill round-trip;
 * gateways populate it when cheap (Spotify Web API home shelves include
 * previews; Apple Music curated rails do too) and leave it `None`
 * otherwise.
 */
export type BrowseFolder = {
  nodeId: string;
  title: string;
  subtitle: string | null;
  artworkId: string | null;
  total: number | null;
  previewChildren: Array<BrowseEntry> | null;
};

/**
 * Page of browse results. `total` is the count of items in the
 * underlying collection when the gateway can cheaply expose it (None
 * means indeterminate). `has_more` is the authoritative end-of-data
 * signal - webapps paginate by raising `offset` until `has_more` is
 * false rather than relying on `total`.
 */
export type BrowseResult = { entries: Array<BrowseEntry>; total: number | null; hasMore: boolean };

/**
 * Why a call ended, surfaced on `onPhoneCallEnded`. `Failed` carries a
 * platform-defined reason (network, busy, etc.).
 */
export type CallEndReason =
  | { type: 'local' }
  | { type: 'remote' }
  | { type: 'missed' }
  | { type: 'declined' }
  | { type: 'failed'; data: { reason: string } };

export type Capabilities = {
  gateway: GatewayInfo | null;
  available: SurfaceAvailability;
  authority: Array<CompanionAuthorityScope>;
  uriSchemes: Array<string>;
  network: NetworkInfo;
  audio: AudioCapabilities;
  musicProvider: MusicProvider;
};

/**
 * What call-control verbs are currently legal. Webapps must gate UI on
 * these flags; sending an unavailable verb is a protocol violation, not
 * a no-op. All `None` = no signal received yet, treat as conservatively
 * unavailable.
 */
export type CommunicationsState = {
  signalStrength: number | null;
  registrationStatus: RegistrationStatus | null;
  airplaneMode: boolean | null;
  carrierName: string | null;
  cellularSupported: boolean | null;
  telephonyEnabled: boolean | null;
  faceTimeAudioEnabled: boolean | null;
  faceTimeVideoEnabled: boolean | null;
  muteStatus: boolean | null;
  currentCallCount: number | null;
  newVoicemailCount: number | null;
  initiateCallAvailable: boolean | null;
  endAndAcceptAvailable: boolean | null;
  holdAndAcceptAvailable: boolean | null;
  swapAvailable: boolean | null;
  mergeAvailable: boolean | null;
  holdAvailable: boolean | null;
};

export type CompanionAuthorityScope = 'nowPlayingMetadata' | 'nowPlayingPlayback' | 'volume';

/**
 * One key/value pair as exposed by config read APIs. `value` is always a
 * string; consumers parse per the field's declared kind (number -> parseFloat,
 * boolean -> "true"/"false", string/enum/secret -> as-is).
 */
export type ConfigEntry = { key: string; value: string };

/**
 * One declared user-tunable setting. Adjacent-tagged on the wire:
 * `{"type":"string","data":{"key":"zip",...}}`.
 */
export type ConfigField =
  | { type: 'string'; data: StringField }
  | { type: 'number'; data: NumberField }
  | { type: 'boolean'; data: BoolField }
  | { type: 'enum'; data: EnumField }
  | { type: 'secret'; data: StringField };

/**
 * The foreground app driving playback, surfaced on iOS over iAP2.
 */
export type CurrentlyActiveApplication = {
  /**
   * Bundle identifier, e.g. `com.spotify.client`.
   */
  id: string;
  name: string;
};

export type Device = { name: string; type: DeviceType; mac: string; default: boolean };

export type DeviceType = 'android' | 'iOS' | 'windows' | 'macOS' | 'linux' | 'unknown';

export type Diagnostics = {
  diskUsedBytes: number;
  diskFreeBytes: number;
  memUsedBytes: number;
  memAvailBytes: number;
  uptimeS: number;
  socTempC: number | null;
  loadAvg: [number, number, number];
  daemonVersion: string;
  kernelVersion: string;
  bootId: string;
};

/**
 * Why a notification went away. `Acted` covers both positive and
 * negative invokes; gateways that distinguish dismiss-vs-acted may
 * surface both as `Acted`.
 */
export type DismissReason = 'userDismissed' | 'acted' | 'remoteDismissed';

/**
 * One key/value pair from a webapp's doc namespace: shared structured
 * state writable from both the companion (gateway) and the webapp
 * itself, last write wins. Values are strings; apps encode JSON as
 * needed.
 */
export type DocEntry = { key: string; value: string };

/**
 * DTMF tones the accessory can play during an active call.
 */
export type DtmfTone = 'd0' | 'd1' | 'd2' | 'd3' | 'd4' | 'd5' | 'd6' | 'd7' | 'd8' | 'd9' | 'star' | 'hash';

/**
 * Direction the accessory wants iOS to take when ending a call.
 */
export type EndCallAction = 'end' | 'endAll';

export type EnumField = { key: string; label: string; choices: Array<string>; default: string | null };

/**
 * Page of the user's favorited / liked / saved library items. Mixed-kind
 * because most platforms expose one "Saved" surface across kinds.
 */
export type FavoritesPage = { items: Array<LibraryItem>; total: number | null; hasMore: boolean };

export type ForwardMessage =
  | { encoding: 'text'; data: string }
  | { encoding: 'json'; data: unknown }
  | { encoding: 'binary'; data: Uint8Array };

export type GatewayCapabilities = {
  gateway: GatewayInfo;
  uriSchemes: Array<string>;
  network: NetworkInfo;
  available: SurfaceAvailability;
  audio: AudioCapabilities;
  musicProvider: MusicProvider;
};

export type GatewayInfo = {
  address: string;
  name: string;
  osName: string;
  appName: string;
  appVersion: string;
  adapterVersion: string;
  libVersion: string;
  libbridgethingVersion: string;
};

/**
 * Subscriber's accuracy preference. `Coarse` opts into the lower-power
 * city-block-grade fix on platforms that distinguish (iOS reduced
 * accuracy, Android `PRIORITY_BALANCED_POWER_ACCURACY`). The daemon
 * aggregates across subscribers and forwards the most-demanding to the
 * companion.
 */
export type GeoAccuracy = 'coarse' | 'fine';

export type GeoError = 'permissionDenied' | 'notDeclared' | 'unavailable' | 'unknownToken';

export type HardwareError = 'levelOutOfRange' | 'modeMismatch';

/**
 * Snapshot of the device's hardware-controlled surfaces. Sent on
 * `hardware.state.get` and re-broadcast on any change. `ambient_level`
 * is the 0-255 ambient light reading.
 */
export type HardwareState = { brightness: BrightnessState; ambientLevel: number };

/**
 * One header on an HTTP request or response. Key order is preserved
 * across serialize/deserialize.
 */
export type HttpHeader = { name: string; value: string };

export type HttpMethod = 'GET' | 'HEAD' | 'POST' | 'PUT' | 'PATCH' | 'DELETE' | 'OPTIONS';

/**
 * An image delivered either as an opaque asset id (fetch via `asset.get`)
 * or as inline bytes.
 */
export type Image = { type: 'id'; data: string } | { type: 'bytes'; data: Uint8Array };

/**
 * What kind of outbound call the accessory wants placed.
 */
export type InitiateCallType = 'destination' | 'voicemail' | 'redial';

/**
 * Coarse type tag a webapp uses to filter or branch. Mirrors the variant
 * names of `LibraryItem`; kept separate so search/recommendations can
 * constrain by kind without having to construct a sample item.
 */
export type ItemKind = 'track' | 'album' | 'playlist' | 'podcastEpisode' | 'show' | 'artist' | 'station';

/**
 * Stable URI + kind a webapp passes back to act on a library item
 * (e.g. `player.play({ uri })`, `library.favorites.toggle({ item })`).
 * `persistent_id` is the platform-stable id when the gateway has one;
 * webapps treat it as opaque.
 */
export type ItemRef = { uri: string; kind: ItemKind; persistentId: string | null };

export type LibraryError =
  | { type: 'notFound'; data: { uri: string } }
  | { type: 'notSupported'; data: { reason: string } }
  | { type: 'unauthorized' }
  | { type: 'noGateway' };

/**
 * One playable / browsable item from the library. Lean per-variant
 * payload - gateways translate platform-specific extras down to these
 * fields, rare per-platform fields just don't surface. Forward-compat:
 * adding new variants or fields is an additive change webapps can
 * branch on.
 */
export type LibraryItem =
  | { type: 'track'; data: Track }
  | { type: 'album'; data: Album }
  | { type: 'playlist'; data: Playlist }
  | { type: 'podcastEpisode'; data: PodcastEpisode }
  | { type: 'show'; data: Show }
  | { type: 'artist'; data: Artist }
  | { type: 'station'; data: Station };

export type LogEntry = { tsUnixS: number; level: LogLevel; target: string; message: string };

export type LogLevel = 'trace' | 'debug' | 'info' | 'warn' | 'error';

export type LogSource = 'daemon' | 'system' | 'all';

/**
 * One timed line. `start_ms` is relative to track start, so a webapp highlights against the
 * same clock it draws the progress bar from.
 */
export type LyricLine = { startMs: number; text: string };

/**
 * Lyrics for one track. `synced` and `plain` are independent: a source may carry either, both,
 * or neither. `source` names the provider so a webapp can attribute it.
 */
export type Lyrics = { synced: Array<LyricLine> | null; plain: string | null; source: string };

/**
 * Currently-playing track, populated to the extent the gateway/iAP2
 * stream has surfaced. All fields are optional because each one arrives
 * as a separate attribute fetch on iAP2; the daemon accumulates and the
 * snapshot reflects whatever's known so far.
 */
export type MediaItem = {
  uri: string | null;
  persistentId: string | null;
  title: string | null;
  album: string | null;
  albumUri: string | null;
  albumArtist: string | null;
  artist: string | null;
  artistUri: string | null;
  liked: boolean | null;
  artworkId: string | null;
  durationMs: number | null;
  mediaTypes: Array<MediaType> | null;
  trackNumber: number | null;
  trackCount: number | null;
  isLikeSupported: boolean | null;
  isBanSupported: boolean | null;
  isBanned: boolean | null;
  chapterCount: number | null;
};

/**
 * Per-track attributes that vary per song. `persistent_id` is a stable
 * per-platform identifier (iAP2 sends u64; we hex-encode it on the
 * wire). `artwork_id` is an opaque asset id - webapps pass this value
 * to `ClientToBridgeAssetMsg::Get` to retrieve the bytes. The id namespace
 * is producer-defined: iAP2 emits `iap2/art/<track_key>/<content_hash>`, the
 * companion picks whatever shape it wants (e.g. `spotify/track/<id>/image`).
 * Webapps treat the value as opaque.
 */
export type MediaItemUpdate = {
  persistentId: string | null;
  title: string | null;
  album: string | null;
  albumUri: string | null;
  albumArtist: string | null;
  artist: string | null;
  artistUri: string | null;
  liked: boolean | null;
  artworkId: string | null;
  durationMs: number | null;
  mediaTypes: Array<MediaType> | null;
  trackNumber: number | null;
  trackCount: number | null;
  isLikeSupported: boolean | null;
  isBanSupported: boolean | null;
  isBanned: boolean | null;
  isResidentOnDevice: boolean | null;
  chapterCount: number | null;
};

/**
 * The kind of media currently playing. Multi-typed: an item can be
 * e.g. both `Podcast` and `AudioBook` (rare). Drives webapp UI choices
 * like skip-15s-vs-skip-track and chapter UI.
 */
export type MediaType = 'music' | 'podcast' | 'audioBook';

export type MusicProvider = 'none' | 'spotify' | 'appleMusic';

export type NetError =
  | { type: 'requestFailed'; data: { reason: string } }
  | { type: 'timeout' }
  | { type: 'unavailable' }
  | { type: 'noGateway' };

export type NetFetchRequest = {
  url: string;
  method: HttpMethod;
  headers: Array<HttpHeader>;
  body?: Uint8Array | null;
  timeoutMs: number | null;
  redirect: RedirectPolicy;
};

export type NetFetchResponse = { status: number; headers: Array<HttpHeader>; body: Uint8Array };

export type NetworkInfo = { kind: NetworkKind; metered: boolean };

export type NetworkKind = 'unknown' | 'wifi' | 'cellular' | 'ethernet';

export type NluAlternate = { intent: string; slots: NluSlots | null };

export type NluAmount = 'small' | 'medium' | 'large';

export type NluDirection = 'up' | 'down';

export type NluPhoneAction = 'answer' | 'decline' | 'end' | 'hold' | 'unhold' | 'swap' | 'merge' | 'mute' | 'unmute';

export type NluPlaybackSpeed = '1' | '1.2' | '1.5' | '2';

export type NluPopularityFilter = 'top5' | 'top10' | 'popular' | 'recent' | 'new' | 'first' | 'random';

export type NluRepeatMode = 'off' | 'all' | 'one';

export type NluResolvedIntent = {
  intent: string;
  slots: NluSlots;
  transcript: string;
  alternates: Array<NluAlternate> | null;
};

export type NluScope = 'previousTrack' | 'restart';

export type NluSlots = {
  target: string | null;
  targetType: NluTargetType | null;
  playlist: string | null;
  genre: string | null;
  mood: string | null;
  era: string | null;
  popularityFilter: NluPopularityFilter | null;
  position: number | null;
  count: number | null;
  scope: NluScope | null;
  enabled: boolean | null;
  mute: boolean | null;
  repeatMode: NluRepeatMode | null;
  seconds: number | null;
  speed: NluPlaybackSpeed | null;
  direction: NluDirection | null;
  amount: NluAmount | null;
  level: number | null;
  preset: string | null;
  view: NluView | null;
  phoneAction: NluPhoneAction | null;
  webappName: string | null;
  uri: string | null;
  contextUri: string | null;
};

export type NluStage = 'fastPath' | 'model' | 'rejectedNoIntent' | 'rejectedClarify' | 'noModel';

export type NluTargetType = 'artist' | 'track' | 'album' | 'playlist' | 'podcast' | 'episode' | 'station';

export type NluView =
  | 'nowPlaying'
  | 'artist'
  | 'album'
  | 'playlist'
  | 'playlists'
  | 'library'
  | 'songs'
  | 'presets'
  | 'queue'
  | 'savedEpisodes'
  | 'newEpisodes';

/**
 * One notification surfaced from the connected companion's notification
 * center. `id` is companion-stable for the lifetime of the notification
 * - webapps pass it to `invokePositive`/`invokeNegative` and listen for
 * `onNotificationRemoved`. Bodies (`title`/`subtitle`/`message`) are all
 * optional because ANCS treats them as separate attribute fetches.
 */
export type Notification = {
  id: string;
  app: NotificationApp;
  category: NotificationCategory;
  title: string | null;
  subtitle: string | null;
  message: string | null;
  timestampUnixS: number | null;
  flags: NotificationFlags;
  positiveAction: NotificationAction | null;
  negativeAction: NotificationAction | null;
};

/**
 * One ANCS-style action slot. `label` is the gateway-localized prompt
 * the webapp renders on the action button.
 */
export type NotificationAction = { label: string };

/**
 * Originating app metadata. `bundle_id` is platform-stable
 * (`com.apple.MobileSMS`, `com.spotify.client`, etc.); `display_name`
 * and `icon_asset_id` are best-effort and may be missing on Android
 * gateways that don't surface them cheaply.
 */
export type NotificationApp = { bundleId: string; displayName: string | null; iconAssetId: string | null };

export type NotificationCategory =
  | 'other'
  | 'incomingCall'
  | 'missedCall'
  | 'voicemail'
  | 'social'
  | 'schedule'
  | 'email'
  | 'news'
  | 'healthAndFitness'
  | 'businessAndFinance'
  | 'location'
  | 'entertainment';

/**
 * ANCS-shaped flags. `silent` mirrors the iOS "do not surface
 * audibly" hint and `important` is the high-importance flag. Only
 * notifications posted while the daemon is connected are surfaced, so
 * there is no pre-existing/backfill marker.
 */
export type NotificationFlags = { silent: boolean; important: boolean };

/**
 * Why a notification action slot could not be invoked. Both invoke verbs are
 * fire-and-forget commands, so a refusal has no reply to ride on.
 */
export type NotificationsError =
  | { type: 'notFound'; data: { id: string } }
  | { type: 'actionRejected'; data: { reason: string } }
  | { type: 'noTarget' };

/**
 * Delta event the companion or iAP2 stream emits whenever a player
 * attribute changes. Every field is optional: producers send partial
 * updates populating only what changed, and fields left unset keep
 * their prior value.
 */
export type NowPlayingUpdate = { mediaItem: MediaItemUpdate | null; playback: PlaybackUpdate | null };

export type NumberField = {
  key: string;
  label: string;
  min: number | null;
  max: number | null;
  step: number | null;
  default: number | null;
};

export type OtaError = {
  code: OtaErrorCode;
  msg: string;
  /**
   * which update failed. a resume re-drives the same artifact, so this is NOT unique per attempt.
   */
  updateId: string | null;
  /**
   * set only when the bridge is re-delivering a failure whose peer had already gone away
   */
  replayed?: boolean;
};

/**
 * Terminal error from the OTA orchestrator
 */
export type OtaErrorCode =
  | 'unknownUpdate'
  | 'offsetMismatch'
  | 'hashMismatch'
  | 'sizeMismatch'
  | 'cancelled'
  | 'writeFailed'
  | 'confirmFailed'
  | 'internal';

/**
 * Terminal success from the OTA orchestrator, emitted for every `OtaKind`.
 */
export type OtaFinished = { kind: OtaKind; updateId: string };

/**
 * What the streamed bytes are going to be applied as
 */
export type OtaKind = 'image' | 'daemon' | 'builtinWebapp' | 'installedWebapp' | 'wakewordModel';

/**
 * Stage of the OTA orchestrator. The phase set is shared between
 * kinds, with non-image kinds emitting a subset
 */
export type OtaPhase = 'streaming' | 'verifying' | 'writing' | 'confirming' | 'reboot';

/**
 * Per-phase progress tick
 */
export type OtaProgress = {
  phase: OtaPhase;
  percent: number;
  step: number;
  nsteps: number;
  dwlPercent: number;
  dwlBytes: number;
  etaMs: number | null;
};

/**
 * Which system overlays the daemon injects into the active webapp's page.
 * Every surface defaults to on, so a minimal webapp gets call / pairing /
 * notification / connection / volume UI for free; a full-service webapp
 * declares off the surfaces it draws itself. The wire events the webapp
 * receives are unchanged either way; this only gates the injected UI.
 */
export type OverlayProfile = {
  /**
   * Notification toasts.
   */
  notifications: boolean;
  /**
   * Incoming / active call banner.
   */
  call: boolean;
  /**
   * Bluetooth pairing PIN modal.
   */
  pairing: boolean;
  /**
   * Companion-disconnected banner, shown only while a paired phone has
   * no useful link.
   */
  connection: boolean;
  /**
   * Transient volume level indicator.
   */
  volume: boolean;
  /**
   * Voice turn indicator: listening, recognizing, and the outcome.
   */
  voice: boolean;
};

export type Peer = {
  device: Device;
  paired: boolean;
  iap2: PeerIap2Status;
  companion: PeerCompanionStatus;
  displayName: string | null;
  language: string | null;
  uuid: string | null;
};

export type PeerCompanionStatus = { type: 'none' } | { type: 'pending' } | { type: 'connected'; data: GatewayInfo };

export type PeerIap2Status = 'none' | 'linkUp' | 'authenticated' | 'identified';

/**
 * One telephony call. `call_id` is companion-stable for the call's
 * lifetime; webapps pass it back to `answer`/`decline`/`end`/`hold`.
 * `remote_id` is the raw E.164 (or platform raw); `display_name` is the
 * gateway's resolved contact name when available.
 */
export type PhoneCall = {
  callId: string;
  remoteId: string;
  displayName: string;
  status: PhoneCallStatus;
  direction: PhoneCallDirection;
  startedAtUnixS: number | null;
  label: string | null;
  addressBookId: string | null;
  service: PhoneCallService | null;
  isConferenced: boolean | null;
  conferenceGroup: number | null;
};

export type PhoneCallDirection = 'incoming' | 'outgoing';

/**
 * Call bearer / service kind. iAP2's `CallStateUpdateService` enum
 * values, projected to our wire surface. Companion gateways that don't
 * distinguish bearers project all calls to `Telephony`.
 */
export type PhoneCallService = 'unknown' | 'telephony' | 'faceTimeAudio' | 'faceTimeVideo';

export type PhoneCallStatus =
  | 'disconnected'
  | 'sending'
  | 'ringing'
  | 'connecting'
  | 'active'
  | 'held'
  | 'disconnecting';

export type PhoneError =
  | { type: 'callNotFound'; data: { call_id: string } }
  | { type: 'actionRejected'; data: { reason: string } }
  | { type: 'noTarget' }
  | { type: 'unavailable'; data: { verb: string } };

/**
 * Snapshot of every active call known to the gateway. Multi-call is
 * possible (call-waiting, conference) - webapps rendering only one
 * active call typically pick the first non-Held entry.
 */
export type PhoneState = { activeCalls: Array<PhoneCall> };

/**
 * Optional context for `play({ uri })`. `context_uri` is the album /
 * playlist / show URI the track is being played from; gateways with
 * playlist support honor it for skip-next semantics. A row inside the
 * context is addressed by playing that row's own uri within it, so there
 * is no index here.
 */
export type PlayContext = { contextUri: string };

/**
 * Per-session playback snapshot: where in the song we are, what mode is
 * engaged. `position_ms` is the live playhead at snapshot time; webapps
 * extrapolate forward locally while `state == Playing`.
 *
 * `set_elapsed_time_available` gates scrub UI: when false, the foreground
 * app refuses absolute-position seeks and webapps must disable the scrub
 * thumb. `None` means unknown (no signal received yet); webapps treat
 * unknown as "available" for backward compatibility with older gateways.
 */
export type Playback = {
  state: PlaybackState;
  positionMs: number;
  positionAgeMs: number | null;
  shuffle: boolean;
  shuffleMode: ShuffleMode | null;
  repeat: RepeatMode;
  queueIndex: number | null;
  queueCount: number | null;
  queueChapterIndex: number | null;
  setElapsedTimeAvailable: boolean | null;
  queueListAvail: boolean | null;
  appleMusicRadioAd: boolean | null;
};

/**
 * What the current track is playing from: the playlist / album / show /
 * artist context. Webapps render "playing from <name>"; `uri` lets them
 * drill into it. `name` is `None` until the companion resolves it.
 */
export type PlaybackContext = { uri: string; name: string | null };

/**
 * Repeat and shuffle toggle state.
 */
export type PlaybackOptions = { repeat: RepeatMode; shuffle: boolean };

/**
 * A resolved queue: the current track flanked by upcoming and previous tracks.
 */
export type PlaybackQueue = { next: Array<Track>; current: Track; previous: Array<Track> };

/**
 * Which player controls the current source supports; webapps disable the
 * UI for any capability that is `false`.
 */
export type PlaybackRestrictions = {
  canRepeatContext: boolean;
  canRepeatTrack: boolean;
  canSeek: boolean;
  canSkipNext: boolean;
  canSkipPrev: boolean;
  canToggleShuffle: boolean;
  canLike: boolean;
  canChangeVolume: boolean;
  canSetOutput: boolean;
};

/**
 * Three-state playback. `Stopped` is the no-track-loaded resting state;
 * `Paused` is "track is loaded, position is held"; `Playing` is the
 * progressing state.
 */
export type PlaybackState = 'stopped' | 'paused' | 'playing';

/**
 * A remote endpoint the current provider can move playback to. Only
 * meaningful when `SurfaceAvailability::playback_targets` is set.
 *
 * `volume_percent` is `None` when the endpoint does not report volume.
 */
export type PlaybackTarget = {
  /**
   * Provider-opaque endpoint id; pass back to `transferTo`.
   */
  id: string;
  name: string;
  kind: PlaybackTargetKind;
  /**
   * Whether this endpoint is the one currently playing.
   */
  isActive: boolean;
  volumePercent: number | null;
};

/**
 * What kind of endpoint a `PlaybackTarget` is. Coarse on purpose: the
 * provider vocabularies (Spotify Connect, AirPlay, Cast) do not agree in
 * their long tails, and webapps only pick an icon from this. Anything
 * unrecognized maps to `Unknown` rather than leaking a provider string.
 */
export type PlaybackTargetKind =
  | 'unknown'
  | 'phone'
  | 'tablet'
  | 'computer'
  | 'speaker'
  | 'tv'
  | 'gameConsole'
  | 'automobile'
  | 'wearable';

/**
 * Per-playback-session attributes that vary regardless of track:
 * playing/paused, position, shuffle/repeat, and the iOS bundle
 * identifier of the app currently driving playback (e.g.
 * `"com.spotify.client"`). `app_bundle` is null on the Android path
 * since it isn't a meaningful surface there.
 *
 * `set_elapsed_time_available` is the gate webapps must honor for
 * scrub UI: when false, scrubbing is unsupported by the foreground
 * app and the seek button must be disabled.
 */
export type PlaybackUpdate = {
  playing: boolean | null;
  positionMs: number | null;
  shuffle: boolean | null;
  shuffleMode: ShuffleMode | null;
  repeat: RepeatMode | null;
  appBundle: string | null;
  appDisplayName: string | null;
  queueIndex: number | null;
  queueCount: number | null;
  queueChapterIndex: number | null;
  playbackSpeed: number | null;
  setElapsedTimeAvailable: boolean | null;
  queueListAvail: boolean | null;
  appleMusicRadioAd: boolean | null;
  appleMusicRadioStationName: string | null;
};

export type PlayerError =
  | { type: 'schemeUnclaimed'; data: { scheme: string } }
  | { type: 'playFailed'; data: { reason: string } }
  | { type: 'noGateway' }
  | { type: 'notInQueue'; data: { index: number } }
  | { type: 'unknownTarget'; data: { target_id: string } };

/**
 * User-tunable knobs that are not "currently playing" state.
 * `crossfade_ms = None` is "crossfade off"; `Some(0)` is also off but
 * distinguishes "user explicitly set zero" from "feature unsupported by
 * gateway".
 */
export type PlayerOptions = { speed: number; crossfadeMs: number | null };

/**
 * Full player snapshot the daemon broadcasts to webapps. Initial value
 * arrives on `BridgeToClientPlayerMsg::StateChange` at connect time;
 * subsequent changes flow as `NowPlayingUpdate` deltas the client SDK
 * merges into the cached snapshot.
 */
export type PlayerState = {
  track: MediaItem | null;
  playback: Playback;
  queue: Array<QueueItem>;
  options: PlayerOptions;
  context: PlaybackContext | null;
  target?: PlaybackTarget | null;
};

/**
 * Lean cross-platform shape for a playlist. `uri` is what `player.play`
 * would route on; `track_count` is best-effort (some sources don't expose
 * it cheaply); `owner_name` is whatever the source surfaces (Spotify
 * owner, Apple Music curator, etc.).
 */
export type Playlist = {
  uri: string;
  name: string;
  ownerName: string | null;
  trackCount: number | null;
  artworkId: string | null;
};

/**
 * One episode of a podcast. `show_name` mirrors what the gateway exposes
 * at episode-level so a webapp can render show + episode without a
 * separate fetch. `published_at_ms` is best-effort; not every gateway
 * surfaces it.
 */
export type PodcastEpisode = {
  uri: string;
  name: string;
  showName: string | null;
  durationMs: number | null;
  publishedAtUnixS: number | null;
  artworkId: string | null;
};

/**
 * One position fix from the gateway. `accuracy_m` is the 1-sigma
 * horizontal radius. `speed_mps` and `heading_deg` are populated when
 * the underlying source provides them (CLLocation on iOS does for moving
 * fixes; Android's FusedLocationProvider similar). `ts_ms` is the
 * gateway-provided fix timestamp, not the wire-arrival time.
 */
export type Position = {
  lat: number;
  lon: number;
  altM: number | null;
  accuracyM: number;
  speedMps: number | null;
  headingDeg: number | null;
  tsUnixS: number;
};

export type Priority = 'normal' | 'bulk' | 'background';

/**
 * One row in the player queue. Lean cross-platform shape - gateways
 * that have richer per-track data still surface what fields they have.
 * `uri` is required because every queued item must be addressable for
 * `skipToIndex`. `persistent_id` is the platform-stable id when
 * available; webapps treat it as opaque.
 */
export type QueueItem = {
  uri: string;
  title: string | null;
  artist: string | null;
  artistUri: string | null;
  album: string | null;
  albumUri: string | null;
  artworkId: string | null;
  durationMs: number | null;
  persistentId: string | null;
  queued: boolean;
};

/**
 * Where in the queue a `queue({ uri })` should land. `Append` (default)
 * goes at the end; `Next` is play-next; `Index(n)` is an explicit 0-based slot
 * in the upcoming list.
 */
export type QueuePosition = { type: 'append' } | { type: 'next' } | { type: 'index'; data: number };

/**
 * Resolved range the companion is about to serve
 */
export type RangePart = { start: number; length: number };

/**
 * Half-open byte range the daemon's range proxy asks the companion to serve
 */
export type RangeSpec = { start: number; length: number };

/**
 * Page of recommendation results. Gateway decides how seed + kind
 * interact (Spotify uses radio-style seeding, Apple Music uses curated
 * rails) - the daemon doesn't prescribe.
 */
export type RecommendationsResult = { items: Array<LibraryItem>; total: number | null; hasMore: boolean };

export type RedirectPolicy = 'follow' | 'manual' | 'error';

/**
 * Cellular registration state - populated from iAP2 `CommunicationsUpdate`
 * or the companion's equivalent.
 */
export type RegistrationStatus =
  | 'unknown'
  | 'notRegistered'
  | 'searching'
  | 'denied'
  | 'registeredHome'
  | 'registeredRoaming'
  | 'emergencyCallsOnly';

/**
 * `repeat` is a typed enum (Off/All/One) shared across the player
 * surface and the iAP2 NowPlaying CSM / MediaSession backends, which
 * all expose three repeat states.
 */
export type RepeatMode = 'off' | 'all' | 'one';

/**
 * Page of search results. `kinds` is the constrained kinds the search
 * honored (echoed back so webapps can detect ignored constraints); items
 * are ranked best-first.
 */
export type SearchResult = {
  items: Array<LibraryItem>;
  kinds: Array<ItemKind>;
  total: number | null;
  hasMore: boolean;
};

/**
 * One podcast show (parent of `PodcastEpisode`). `episode_count` is
 * best-effort.
 */
export type Show = {
  uri: string;
  name: string;
  publisher: string | null;
  episodeCount: number | null;
  artworkId: string | null;
};

/**
 * Three-state shuffle. iAP2 and Apple Music distinguish track-level
 * from album-level shuffle; companion gateways without that distinction
 * project to `Songs` when on. Webapps that just need an on/off signal
 * read `shuffle_on` (None when the underlying mode is unknown).
 */
export type ShuffleMode = 'off' | 'songs' | 'albums';

/**
 * Algorithmic / radio station. `seed` is the URI the station was seeded
 * from when known (artist, track, etc.).
 */
export type Station = { uri: string; name: string; seed: string | null; artworkId: string | null };

/**
 * First event of an open stream. Carries the response status, headers,
 * and (when known) total payload size so the consumer can preallocate
 * or display progress. Subsequent `StreamChunk` and `StreamEnd` events
 * for the same `stream_id` follow.
 */
export type StreamBegin = { streamId: string; status: number; headers: Array<HttpHeader>; totalSize: number | null };

/**
 * One body chunk. Chunks arrive in order; `offset` is the byte
 * position of `bytes[0]` within the full body.
 */
export type StreamChunk = { streamId: string; offset: number; bytes: Uint8Array };

/**
 * Terminates a stream. After `End` no further chunks for `stream_id`
 * are valid and the daemon clears its routing entry.
 */
export type StreamEnd = { streamId: string };

/**
 * Stream failed mid-flight (or before the first byte). Terminal - the
 * daemon clears its routing entry. The `error` shape is shared with
 * `fetch` since the failure modes are identical.
 */
export type StreamError = { streamId: string; error: NetError };

export type StringField = {
  key: string;
  label: string;
  pattern: string | null;
  minLength: number | null;
  maxLength: number | null;
  default: string | null;
};

export type SurfaceAvailability = {
  geo: boolean;
  notifications: boolean;
  netFetch: boolean;
  netWs: boolean;
  audioTts: boolean;
  lyrics: boolean;
  playbackTargets: boolean;
};

/**
 * Wall clock + locale snapshot. `wall_clock_unix_s` is the gateway's
 * (or iAP2 device's) claimed "now" in unix-epoch seconds - webapps
 * reading time should use the device clock if any but use this as the
 * trust anchor on first arrival.
 *
 * Two zone-identification paths coexist: companion gateways send
 * `tz_iana` (an IANA zone identifier like `America/Denver`) while iAP2
 * `DeviceTimeUpdate` only exposes numeric `utc_offset_minutes` plus a
 * separate `dst_offset_minutes`. Webapps prefer `tz_iana` when present
 * and fall back to the offset pair.
 */
export type TimeInfo = {
  tzIana: string | null;
  locale: string | null;
  wallClockUnixS: number | null;
  utcOffsetMinutes: number | null;
  dstOffsetMinutes: number | null;
};

/**
 * A track with resolved album/artist metadata, used by library search
 * and browse results. For live now-playing state see `MediaItem`.
 */
export type Track = {
  id: string;
  name: string;
  album: Album;
  /**
   * Primary credited artist.
   */
  artist: Artist;
  /**
   * All credited artists, in order.
   */
  artists: Array<Artist>;
  durationMs: number;
  /**
   * Opaque artwork asset id; pass to `asset.get` for the bytes.
   */
  imageId: string;
  /**
   * Whether the track is saved in the user's library.
   */
  saved: boolean;
};

export type TtlRetention = { seconds: number };

export type TunnelAck = { tunnelId: string; consumed: number };

export type TunnelClosed = { tunnelId: string; reason: string | null };

export type TunnelData = { tunnelId: string; bytes: Uint8Array };

export type TunnelError =
  | { type: 'connectFailed'; data: { reason: string } }
  | { type: 'permissionDenied' }
  | { type: 'unavailable' };

export type VoiceCaptureReason = 'pushToTalk' | 'assistant' | 'wakeWord';

export type VoiceDescriptor = { id: string; name: string; locale: string };

export type VoiceDispatchErrorCode =
  | 'webappNotFound'
  | 'notDispatchable'
  | 'unsupported'
  | 'playbackFailed'
  | 'badSlots'
  | 'internal';

/**
 * Where the daemon actually routed a successful dispatch
 */
export type VoiceDispatchTarget = 'playback' | 'device' | 'phone' | 'display' | 'webappSwitch';

/**
 * Domain errors emitted by any webapp surface (gateway- or client-side).
 * Single catalog: both protocols speak the same variant set.
 */
export type WebappError =
  | { type: 'webappNotFound'; data: { id: string } }
  | { type: 'cannotUninstallBuiltin'; data: { id: string } }
  | { type: 'idReserved'; data: { id: string } }
  | { type: 'extractedTooLarge'; data: { max_bytes: number } }
  | { type: 'provenanceTooLong'; data: { max_bytes: number } }
  | { type: 'zipMalformed'; data: { reason: string } }
  | { type: 'missingIndexHtml' }
  | { type: 'invalidManifest'; data: { reason: string } }
  | { type: 'resourceNotAvailable'; data: { id: string } }
  | { type: 'notALauncher'; data: { id: string } }
  | { type: 'noOverlay'; data: { id: string } }
  | { type: 'unknownConfigKey'; data: { key: string } }
  | { type: 'invalidConfigValue'; data: { key: string; reason: string } }
  | { type: 'invalidDocValue'; data: { key: string; reason: string } }
  | { type: 'internal'; data: { reason: string } };

export type WebappInfo = {
  id: string;
  name: string;
  source: WebappSource;
  role: WebappRole;
  version: string;
  description: string | null;
  iconHash: string | null;
  settingsHash: string | null;
  overlayHash: string | null;
  config: Array<ConfigField>;
  permissions: Array<string>;
  rendersVoiceDisplay: boolean;
  art: ArtProfile | null;
  provenance: string | null;
};

/**
 * On-disk `manifest.json` shape. Read from the bundle at install time
 * and validated; the resulting metadata projects to `WebappInfo` for
 * the wire.
 */
export type WebappManifest = {
  id: string;
  name: string;
  version: string;
  description: string | null;
  icon: string | null;
  settings: string | null;
  overlay: string | null;
  role: WebappRole;
  config: Array<ConfigField>;
  permissions: Array<string>;
  rendersVoiceDisplay: boolean;
  art?: ArtProfile | null;
  overlays: OverlayProfile;
};

/**
 * A webapp's launcher visibility. `Standard` shows up in user-facing
 * listings (the hub grid, etc); `Launcher` is itself a launcher and is
 * hidden from those listings. The daemon filters `Launcher` bundles
 * out of `client.webapp.list`; the gateway list keeps everything.
 * Declaring `Launcher` is also what makes a bundle eligible for the
 * device's launcher slot.
 */
export type WebappRole = 'standard' | 'launcher';

export type WebappSource = 'builtin' | 'installed';

export type WsError =
  | { type: 'connectFailed'; data: { reason: string } }
  | { type: 'frameTooLarge' }
  | { type: 'gatewayDisconnected' }
  | { type: 'protocolError'; data: { reason: string } };

export type WsFrame = { type: 'text'; data: string } | { type: 'binary'; data: Uint8Array };
