// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StockPreset = {
  context_uri: string;
  image_url: string | null;
  /**
   * Slot 1 to 4.
   */
  slot_index: number;
  name: string | null;
  description: string | null;
};

export type StockSetPreset = {
  /**
   * Payload version. Send 1.
   */
  version: number;
  context_uri: string;
  /**
   * Slot 1 to 4. The daemon ignores others.
   */
  slot_index: number;
  /**
   * `tactile` or `voice`.
   */
  source: string;
};
